### ISSUE TITLE
Files Missing in graph_gen.ipynb

### ISSUE THREAD

**Issue by steveysfeng** [pat-jj/GraphCare#1]
I'm using the graph_gen.ipynb file to generate some graphs, but I'm running into an issue where some files seem to be missing. Specifically, the files in the following code snippet are not being found:

with open('../../clinical_notes/subject_text_dict.json', 'r') as f:
    subject_text_dict = json.load(f)

for key in tqdm(subject_text_dict.keys()):
    file = f'../../graphs/notes/{key}.txt'q
    notes = subject_text_dict[key]

I'm not sure why this is happening, but I would appreciate any help in figuring out how to fix it. Can someone please provide some guidance on what might be causing this issue and how to resolve it? Thank you!

**Comment by pat-jj** [comment]
Hi, thanks for your interest in our work! We're not using clinical notes but only the structured EHR in this work, and you can basically skip the blocks related to that for now. If you're interested in the extension of incorporating the clinical notes in graph generation, we will definitely provide the processing script soon.

**Comment by ArtificialZeng** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '../../clinical_notes/subject_text_dict.json'

**Comment by ArtificialZeng** [comment]
> I'm using the graph_gen.ipynb file to generate some graphs, but I'm running into an issue where some files seem to be missing. Specifically, the files in the following code snippet are not being found:
> 
> with open('../../clinical_notes/subject_text_dict.json', 'r') as f: subject_text_dict = json.load(f)
> 
> for key in tqdm(subject_text_dict.keys()): file = f'../../graphs/notes/{key}.txt'q notes = subject_text_dict[key]
> 
> I'm not sure why this is happening, but I would appreciate any help in figuring out how to fix it. Can someone please provide some guidance on what might be causing this issue and how to resolve it? Thank you!

have You solved that?
