### ISSUE TITLE
buggy code, No ent2id.json

### ISSUE THREAD

**Issue by ArtificialZeng** [pat-jj/GraphCare#10]
when i finally solved the bug : python .\data_prepare.py
Dataset: mimic3, Task: mortality
Load processed dataset: False
Load cluster: True
Save cluster: False
Save graph: True
Save processed dataset: True
Loading dataset...
Parsing PATIENTS and ADMISSIONS: 100%|███████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1207.90it/s]
Parsing DIAGNOSES_ICD: 100%|████████████████████████████████████████████████████████████████████████████████| 129/129 [00:00<00:00, 12167.79it/s] 
Parsing PROCEDURES_ICD: 100%|███████████████████████████████████████████████████████████████████████████████| 113/113 [00:00<00:00, 22075.28it/s]
Parsing PRESCRIPTIONS: 100%|██████████████████████████████████████████████████████████████████████████████████| 122/122 [00:00<00:00, 199.41it/s]
Mapping codes: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1582.21it/s] 
Generating samples for mortality_prediction_mimic3_fn: 100%|███████████████████████████████████████████████████████████| 100/100 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "D:\A_ShenZhou_Work\GraphCare\data_prepare.py", line 527, in <module>
    main()
  File "D:\A_ShenZhou_Work\GraphCare\data_prepare.py", line 523, in main
    run(dataset, task)
  File "D:\A_ShenZhou_Work\GraphCare\data_prepare.py", line 489, in run
    sample_dataset = load_dataset(load_processed_dataset, dataset=dataset, task=task)
  File "D:\A_ShenZhou_Work\GraphCare\data_prepare.py", line 86, in load_dataset
    sample_dataset = ds.set_task(mortality_prediction_mimic3_fn)
  File "D:\A_IDE\anaconda3\envs\GraphCare\lib\site-packages\pyhealth\datasets\base_dataset.py", line 360, in set_task
    sample_dataset = SampleDataset(samples,
  File "D:\A_IDE\anaconda3\envs\GraphCare\lib\site-packages\pyhealth\datasets\sample_dataset.py", line 46, in __init__
    self.input_info: Dict = self._validate()
  File "D:\A_IDE\anaconda3\envs\GraphCare\lib\site-packages\pyhealth\datasets\sample_dataset.py", line 68, in _validate
    keys = self.samples[0].keys()
IndexError: list index out of range

Then I got:

Generated 0 samples for patient 44154
patientidddddddd, 44212
Patient 44212 has 1 visits
Generated 0 samples for patient 44212
patientidddddddd, 44222
Patient 44222 has 1 visits
Generated 0 samples for patient 44222
patientidddddddd, 44228
Patient 44228 has 1 visits
Generated 0 samples for patient 44228
Warning: Empty sample list. Skipping validation and indexing.
Traceback (most recent call last):
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 530, in <module>
    main()
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 526, in main
    run(dataset, task)
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 495, in run
    ent2id, rel2id, ent_emb, rel_emb = load_embeddings(task)
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 154, in load_embeddings
    with open('./graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/ent2id.json', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/ent2id.json'
dataset: mimic3
Loading embeddings...

Process finished with exit code 1

**Comment by ArtificialZeng** [comment]
No such file or directory: './graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/ent2id.json'

**Comment by pat-jj** [comment]
Please run `./graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/merge.ipynb` first.

**Comment by ArtificialZeng** [comment]
> Please run `./graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/merge.ipynb` first.

thank you very much. pls upload all the data, pls. It's hard to run the whole process.

**Comment by pat-jj** [comment]
Once we get enough bandwidth, we will upload it with its ethical checking done. We will also update our repo to make it more user-friendly. Thanks for your patience.

**Comment by ArtificialZeng** [comment]
> Please run `./graphs/cond_proc_drug/CCSCM_CCSPROC_ATC3/merge.ipynb` first.

still buggy：
FileNotFoundError: [Errno 2] No such file or directory: '../../condition/CCSCM/id2ent.json'

**Comment by pat-jj** [comment]
You should run `/graphcare_/graph_generation/{cond,proc,drug}_emb_ret.ipynb` to get this file, as pointed out in README 1.3.

**Comment by ArtificialZeng** [comment]
> Once we get enough bandwidth, we will upload it with its ethical checking done. We will also update our repo to make it more user-friendly. Thanks for your patience.

when  you get enough bandwidth, pls
