### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by comfilcon** [pat-jj/GraphCare#12]
This is an overall great work! I've reproduced most results (some are even higher than the reported ones).
However, there are some issues I found in the current code space:

1. `attention_init.ipynb`: It does not match what's done in Appendix C.3 Table 4. I guess it's not the latest version, and the author probably needs to update it.
2. `ChatGPT.py`: It shows you're using gpt-3.5-turbo instead of gpt-4, which is inconsistent with your paper, but it's only a minor issue.
3. You need to sort your code! The file paths are messy and most of them are absolute paths, which definitely impedes the reproduction a lot.

Here's also a suggestion for future work:
Hallucination is still a problem. You can consider the following pipeline to make it more reliable:
- RAG -> Graph Construction -> Prediction

**Comment by pat-jj** [comment]
Thanks a lot for the suggestions! We're also glad to know that Claude can do a great job, and will definitely give it a try.
For the RAG-powered approach, I think there are already some relevant works:

1. `Xu, Ran, et al. "RAM-EHR: Retrieval Augmentation Meets Clinical Predictions on Electronic Health Records." arXiv preprint arXiv:2403.00815 (2024).`
2. `Zhu, Yinghao, et al. "REALM: RAG-Driven Enhancement of Multimodal Electronic Health Records Analysis via Large Language Models." arXiv preprint arXiv:2402.07016 (2024).`

By the way, we will sort our code when we get sufficient bandwidth to do so. Thank you!
