### ISSUE TITLE
Hardware usage

### ISSUE THREAD

**Issue by KyunghoonJeon** [pat-jj/GraphCare#15]
Hello
Thank you for the great paper work.
I am slightly overwhelmed by the hardware usage that was written in the appendix. 
Can you verify how much memory was used while training?
Using 528GB ram and eight A6000 GPUs does not convince me when analyzing the model. 
Can you give details how much memory you used while running the model? 

Thank you.

**Comment by KyunghoonJeon** [comment]
Also can I have a clue of the training time and inference time? Thank you

**Comment by pat-jj** [comment]
The training time for one epoch is ~2 mins for MIMIC-III mortality prediction.
