### ISSUE TITLE
Multi-visit patient processing in data_prepare

### ISSUE THREAD

**Issue by caizicharles** [pat-jj/GraphCare#17]
Hello! Thank you for the great work!

I have a question regarding the number of visits contained within every patient, it is clear from your paper that each patient may include more than one visit and beta explicitly captures the importance of the j-th visit of the i-th patient. Unfortunately, after looking into data_prepare.py and task_fn.py, **for certain tasks, it seemed that each sample in the sample_dataset is a patient that only has 1 visit.**

It can be seen that you have used pyhealth BaseEHRDataset's set_task method to generate the labels and the patient samples, but customized the task_fns:

<img width="598" alt="Screenshot 2024-09-06 at 11 48 29" 
src="https://github.com/user-attachments/assets/35c8ea93-31bd-4c59-90b5-95f5db4c28c8">

<img width="1036" alt="Screenshot 2024-09-06 at 11 49 57" src="https://github.com/user-attachments/assets/bdb19e6a-ba5a-47a6-85ce-10946263e99d">

Here are 2 examples where the first image below indicates that "sliding visit window" is used, and each sample includes more than 1 visits. The second, however, shows that for some tasks, each sample only has 1 visit.

<img width="507" alt="Screenshot 2024-09-06 at 11 49 19" src="https://github.com/user-attachments/assets/612715db-eaa5-4d4a-b499-a17d91df4b83">

<img width="587" alt="Screenshot 2024-09-06 at 11 56 26" src="https://github.com/user-attachments/assets/0136a275-f95e-4e1c-a95f-1bc2aef9ae0e">

I acknowledge that the process_sample_dataset fn in data_prepare.py will take each sample, and according to the len/number of visits in each sample, add to the medical code node set of that patient to generate these attributes, but if each sample's conditions/procedures/drugs is only len 1, then this notion is moot. It would be great if you could explain how multi-visit is considered for tasks like mimic-iii readmission and length of stay, perhaps I missed something.

<img width="418" alt="Screenshot 2024-09-06 at 12 00 08" src="https://github.com/user-attachments/assets/75bcf4bb-3936-4fbb-a023-eeb98782d96b">
<img width="543" alt="Screenshot 2024-09-06 at 11 59 44" src="https://github.com/user-attachments/assets/f13149f2-4e54-4950-86f7-3ee05c328be3">

**Comment by pat-jj** [comment]
Hi, thank you for your question. Each sample indicates a single visit (even for the drug recommendation task). The process of multiple visits for the same patient is in a later process. I will get back to you with details after the ICLR deadline this year if you still have questions.

**Comment by pat-jj** [comment]
Thank you for your question. The "add history" code can be applied to all task functions. If it's missing in certain tasks, it might be due to our testing of single-visit-based prediction cases.

**Comment by LeiGong0125Carrot** [comment]
does this mean that you train the model using the patient-level graphs which include all of the visit for each patient, and for testing used the single visit graph?

**Comment by caizicharles** [comment]
My task formulation is different, I essentially used all visits of a patient to construct the patient graph to predict targets of the final visit

**Comment by LeiGong0125Carrot** [comment]
> does this mean that you train the model using the patient-level graphs which include all of the visit for each patient, and for testing used the single visit graph?

does this mean that you train the model using the patient-level graphs which include all of the visit for each patient, and for testing used the single visit graph?

**Comment by caizicharles** [comment]
no, training and testing settings are the same, all visits used

**Comment by LeiGong0125Carrot** [comment]
> Thank you for your question. The "add history" code can be applied to all task functions. If it's missing in certain tasks, it might be due to our testing of single-visit-based prediction cases.

does this mean that you train the model using the patient-level graphs which include all of the visit for each patient, and for testing used the single visit graph?
