### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../clinical_notes/subject_text_dict.json'

### ISSUE THREAD

**Issue by ArtificialZeng** [pat-jj/GraphCare#4]
FileNotFoundError: [Errno 2] No such file or directory: '../../clinical_notes/subject_text_dict.json'

**Comment by pat-jj** [comment]
I've removed the block causing this error and making the confusion. 
We did not use clinical notes in our work.
Please re-check `graph_gen.ipynb`.
Thanks you!
