### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../condition/CCSCM/id2ent.json'

### ISSUE THREAD

**Issue by ArtificialZeng** [pat-jj/GraphCare#7]
Imcomplete file uploading

**Comment by pat-jj** [comment]
Please use `/graphcare_/graph_generation/{cond,proc,drug}_emb_ret.ipynb` to get those files. Thanks.

**Comment by ArtificialZeng** [comment]
> Please use `/graphcare_/graph_generation/{cond,proc,drug}_emb_ret.ipynb` to get those files. Thanks.

When I run proc_emb_ret.ipynb, it gets:
FileNotFoundError: [Errno 2] No such file or directory: '../../graphs/procedure/CCSPROC/1.txt'

**Comment by pat-jj** [comment]
You need to generate those knowledge graphs from graph_gen.ipynb first.
