### ISSUE TITLE
All processed data for Training and Prediction

### ISSUE THREAD

**Issue by quqxui** [pat-jj/GraphCare#8]
Hi, Thanks for your efforts to this project.  

I kindly request that you upload all the processed data from Step 1 and 2. Having access to this data would greatly assist us in directly running the Training and Prediction steps, making it easier for us to reproduce your work. 

Thank you in advance for your consideration.

**Comment by pat-jj** [comment]
Hi, thank you for your interest in this work. 
There are always ethical concerns regarding data generated by GPT, and we need to perform an ethics review before publicizing all the processed files.
We will release them when they are ready.
Currently, all the files needed toward reproduction can be generated by following steps described by readme.

**Comment by ArtificialZeng** [comment]
> Can you provide the data to directly run `python graphcare.py ` and `python ehr_models.py`? It is find to only provide the processed UMLS-KG, without GPT-KG.

I have all the data

**Comment by angushhz** [comment]
Hi @ArtificialZeng
 Would it possible for you to share me data which would spend time on reproducing result ?
Many thanks.
