### ISSUE TITLE
data_prepare跑不通哇

### ISSUE THREAD

**Issue by ArtificialZeng** [pat-jj/GraphCare#9]
Returning empty samples list
list_dict[table]: [Event with CCSCM code 13 from table DIAGNOSES_ICD, Event with CCSCM code 131 from table DIAGNOSES_ICD, Event with CCSCM code 98 from table DIAGNOSES_ICD, Event with CCSCM code 53 from table DIAGNOSES_ICD]
list_dict[table]: [Event with CCSPROC code 74 from table PROCEDURES_ICD, Event with CCSPROC code 70 from table PROCEDURES_ICD, Event with CCSPROC code 39 from table PROCEDURES_ICD, Event with CCSPROC code 223 from table PROCEDURES_ICD]
list_dict[table]: []
Visit 1:
Conditions: ['13', '131', '98', '53']
Procedures: ['74', '70', '39', '223']
Drugs: []
Skipping visit due to missing data
list_dict[table]: [Event with CCSCM code 130 from table DIAGNOSES_ICD, Event with CCSCM code 97 from table DIAGNOSES_ICD, Event with CCSCM code 98 from table DIAGNOSES_ICD, Event with CCSCM code 59 from table DIAGNOSES_ICD, Event with CCSCM code 12 from table DIAGNOSES_ICD]
list_dict[table]: [Event with CCSPROC code 47 from table PROCEDURES_ICD, Event with CCSPROC code 39 from table PROCEDURES_ICD, Event with CCSPROC code 63 from table PROCEDURES_ICD]
list_dict[table]: []
Visit 2:
Conditions: ['130', '97', '98', '59', '12']
Procedures: ['47', '39', '63']
Drugs: []
Skipping visit due to missing data
Number of samples: 0
Returning empty samples list
Number of samples: 0
Returning empty samples list
Number of samples: 0
Returning empty samples list
Number of samples: 0
Returning empty samples list
Number of samples: 0
Returning empty samples list
11111111111111: []
Generating samples for mortality_prediction_mimic3_fn: 100%|██████████| 100/100 [00:00<00:00, 9606.96it/s]
Traceback (most recent call last):
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 529, in <module>
    main()
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 525, in main
    run(dataset, task)
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 491, in run
    sample_dataset = load_dataset(load_processed_dataset, dataset=dataset, task=task)
  File "D:\googleDownloads\GraphCare-main\GraphCare-main\data_prepare.py", line 88, in load_dataset
    sample_dataset = ds.set_task(mortality_prediction_mimic3_fn)
  File "D:\A_IDE\anaconda3\lib\site-packages\pyhealth\datasets\base_dataset.py", line 360, in set_task
    sample_dataset = SampleDataset(samples,
  File "D:\A_IDE\anaconda3\lib\site-packages\pyhealth\datasets\sample_dataset.py", line 46, in __init__
    self.input_info: Dict = self._validate()
  File "D:\A_IDE\anaconda3\lib\site-packages\pyhealth\datasets\sample_dataset.py", line 69, in _validate
    print(self.samples[0].keys())
IndexError: list index out of range

Process finished with exit code 1

**Comment by pat-jj** [comment]
I see you have already solved it in this [issue](https://github.com/pat-jj/GraphCare/issues/10), so I close it.
